### ISSUE TITLE
validate error on other field

### ISSUE THREAD

**Issue by anyway111** [inimist/cakephp-captcha#3]
I use cakephp-captcha for login form,
when i have not use cakephp-captcha i can login normal. but after i use it i can't login
rule isUnique of email that apply. although, i use  $this->User->validator()->remove('email', 'isUnique') for remove rule isUnique but it can not remove.
i think because in method beforeValidate() of CaptchaBehavior. it's setting $model->validate include rule isUnique.
how do remove it?

**Comment by inimist** [comment]
It is setting a new rule validateCaptcha in the beforeValidate() function of captcha behavior. I am not sure what problem you are facing though. Do I have a link to view it or the code you are putting there?

**Comment by anyway111** [comment]
I have fix it by use $model->validator()->remove('email', 'isUnique') in method beforeValidate() of CaptchaBehavior to remove it.
although, this is a temporary solution, if i want to use CaptchaBehavior for other Model it's not favorable
I think you can add a logic to remove rule from Controller if users whose want so.
